<?php
/**
 * api/call/accept.php
 *
 * Admin accepts a pending call.  Stores the WebRTC SDP answer and marks the
 * session as active, preventing other admins from answering the same call.
 *
 * POST params (admin must be logged in):
 *   call_id    (int)    – ID from call_sessions
 *   answer_sdp (string) – WebRTC SDP answer generated by admin browser
 */

header('Content-Type: application/json');
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/functions.php';

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'message' => 'Method not allowed']);
    exit;
}

if (!isLoggedIn()) {
    http_response_code(401);
    echo json_encode(['success' => false, 'message' => 'Unauthorized']);
    exit;
}

$call_id    = isset($_POST['call_id'])    ? (int)$_POST['call_id']        : 0;
$answer_sdp = trim($_POST['answer_sdp']  ?? '');

if ($call_id <= 0 || empty($answer_sdp)) {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'call_id and answer_sdp are required']);
    exit;
}

try {
    $db = getDB();

    $current_user = getCurrentUser();
    $admin_id     = (int)$current_user['id'];

    // Accept only if still pending (prevents double-accept race condition)
    $stmt = $db->prepare(
        "UPDATE call_sessions
         SET status = 'active', accepted_by = ?, answer_sdp = ?
         WHERE id = ? AND status = 'pending'"
    );
    $stmt->execute([$admin_id, $answer_sdp, $call_id]);

    if ($stmt->rowCount() === 0) {
        // Either already accepted or doesn't exist
        $check = $db->prepare("SELECT status, accepted_by FROM call_sessions WHERE id = ?");
        $check->execute([$call_id]);
        $row = $check->fetch();

        if (!$row) {
            echo json_encode(['success' => false, 'message' => 'Call session not found']);
        } else {
            echo json_encode([
                'success'     => false,
                'message'     => 'Call already accepted by another admin',
                'status'      => $row['status'],
                'accepted_by' => $row['accepted_by'],
            ]);
        }
        exit;
    }

    logActivity($admin_id, 'Accepted incoming call', 'call_sessions', $call_id);

    echo json_encode(['success' => true, 'call_id' => $call_id]);
} catch (\Throwable $e) {
    error_log('call/accept.php error: ' . $e->getMessage());
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Server error']);
}
